version: "3"

services:
  db:
    container_name: mdf_db
    image: postgres:13.3
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5438:5432"
  web:
    container_name: mdf_server
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python manage.py makemigrations && python manage.py migrate && gunicorn mdf_server.wsgi -b 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: